#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build

echo -e "===\n>> Pre-push Hook: Checking branch name / Mengecek nama branch..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
ISASTROARTICLE=\astro-article$
ISGATSBYARTICLE=\gatsby-article$
ISASTRODEV=\dev-astro$
ISGATSBYDEV=\dev$


if [[ "$BRANCH" =~ $ISASTROARTICLE ]]
then
  git push origin dev-astro
fi

if [[ "$BRANCH" =~ $ISASTRODEV ]]
then
  git push origin astro-article
fi

if [[ "$BRANCH" =~ $ISGATSBYARTICLE ]]
then
  git push origin dev
fi

if [[ "$BRANCH" =~ $ISGATSBYDEV ]]
then
  git push origin gatsby-article
fi

echo -e ">> Finish checking branch name / Selesai mengecek nama branch.\n==="

exit 0
