# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy astro

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: checkout astro
        run: git fetch && git checkout dev-astro

      - name: Installing my packages
        run: yarn install

      - name: Build my App
        run: yarn build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          # NEXT_PUBLIC_BASE_PATH: /revamp
      # - run: npm run export
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      # NEXT_PUBLIC_BASE_PATH: /revamp
      - run: touch ./dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
